ack alias 거는 명령어 더 깔끔하게

diff --git a/zsh/zshrc b/zsh/zshrc
--- a/zsh/zshrc
+++ b/zsh/zshrc
@@ -173,13 +173,10 @@ function Shell::alias {
 	# linux : ack-grep
 	# osx : ack
 	unalias ack 2> /dev/null
-	which ack > /dev/null 2> /dev/null
-	ack_exist_retval=$?
-	which ack-grep > /dev/null 2> /dev/null
-	ack_grep_exist_retval=$?
-
-	if [ $ack_grep_exist_retval == 0 ] && [ $ack_exist_retval != 0 ]; then
-		echo "[Shell] ack-grep found, ack not found => enable ack alias"
+	ack_exist=$(which ack > /dev/null 2> /dev/null; echo $?)
+	ack_grep_exist=$(which ack-grep > /dev/null 2> /dev/null; echo $?)
+	if [[ $ack_grep_exist == "0" ]] && [[ $ack_exist != "0" ]]; then
+		echo "[Shell]\t ack-grep found, ack not found => enable ack alias"
 		alias ack='ack-grep'
 	fi
 
